when:
  event: [manual, push, pull_request]
  branch: main
  path: [.woodpecker/build.yaml, .woodpecker/push.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]

matrix:
  PLATFORM: [amd64, arm64]
labels:
  platform: linux/${PLATFORM}

steps:

  build:
    image: gcr.io/kaniko-project/executor:v1.23.2-debug
    commands: /kaniko/executor
        --context=$CI_WORKSPACE
        --destination=ci-registry.schnabel.org/kokuwaio/yamllint:$CI_PIPELINE_NUMBER-$PLATFORM
        --reproducible
        --cache
        --cache-copy-layers
        --cache-run-layers
        --cache-repo=$DOCKER_CACHE/cache/kokuwaio/yamllint
        --insecure-registry=$DOCKER_CACHE
        --insecure-registry=$DOCKER_MIRROR
        --registry-mirror=$DOCKER_MIRROR
        --skip-default-registry-fallback
        --label=org.opencontainers.image.title="Yamllint Plugin"
        --label=org.opencontainers.image.description="A Woodpecker CI plugin for yamllint to lint yaml files."
        --label=org.opencontainers.image.url=$CI_REPO_URL
        --label=org.opencontainers.image.documentation=$CI_REPO_URL
        --label=org.opencontainers.image.source=$CI_REPO_CLONE_URL
        --label=org.opencontainers.image.vendor=kokuwa.io
        --label=org.opencontainers.image.licenses=GPL-3.0-or-later
        --label=org.opencontainers.image.version=1.37.0

  test:
    image: ci-registry.schnabel.org/kokuwaio/yamllint:${CI_PIPELINE_NUMBER}-${PLATFORM}
    pull: true
