when:
  event: [manual, push, pull_request]
  branch: main
  path: [.woodpecker/lint.yaml, renovate.json, Dockerfile, "**/*.yaml", "**/*.md", "**/*.sh"]

steps:

  renovate:
    image: kokuwaio/renovate-config-validator:41
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, renovate.json]]

  dockerfile:
    image: kokuwaio/hadolint:v2.14.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, Dockerfile]]

  yaml:
    image: kokuwaio/yamllint:v1.37.1
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.yaml"]]

  markdown:
    image: kokuwaio/markdownlint:0.45.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.md", .markdownlint.yaml]]

  shellcheck:
    image: kokuwaio/shellcheck:v0.11.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.sh"]]
