when:
  event: [manual, push, pull_request]
  branch: main
  path: [.woodpecker/lint.yaml, renovate.json, "**/*.yaml", "**/*.md", "**/*.sh", "**/Dockerfile"]

steps:

  renovate:
    image: kokuwaio/renovate-config-validator:41
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, renovate.json]]

  yaml:
    image: kokuwaio/yamllint:v1.37.1
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, .yamllint.yaml, "**/*.yaml"]]

  markdown:
    image: kokuwaio/markdownlint:0.45.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, .markdownlint.yaml, "**/*.md"]]

  dockerfile:
    image: kokuwaio/hadolint:v2.12.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/Dockerfile"]]

  shellcheck:
    image: kokuwaio/shellcheck:v0.10.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.sh"]]
