when:
  instance: ci.schnabel.org
  repo: kokuwaio/yamllint
  event: push
  branch: main
  path: [.woodpecker/build.yaml, .woodpecker/push.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]

depends_on: [build]
skip_clone: true

steps:

  manifest:
    image: mplatform/manifest-tool:alpine-v2.1.9
    commands: manifest-tool push from-args
        --platforms=linux/amd64,linux/arm64
        --template=ci-registry.schnabel.org/kokuwaio/yamllint:$CI_PIPELINE_NUMBER-ARCH
        --target=ci-registry.schnabel.org/kokuwaio/yamllint:$CI_PIPELINE_NUMBER

  docker.io: &push
    image: quay.io/skopeo/stable:v1.18.0
    depends_on: [manifest]
    commands:
      - echo "$AUTH" > /tmp/auth.json
      - skopeo copy --all --preserve-digests --dest-precompute-digests
          docker://ci-registry.schnabel.org/kokuwaio/yamllint:$CI_PIPELINE_NUMBER
          docker://$URL/kokuwaio/yamllint:1.37.0
      - skopeo copy --all --preserve-digests --dest-precompute-digests
          docker://ci-registry.schnabel.org/kokuwaio/yamllint:$CI_PIPELINE_NUMBER
          docker://$URL/kokuwaio/yamllint:latest
    environment:
      URL: docker.io
      AUTH: {from_secret: DOCKER_IO_AUTH}

  ghcr.io:
    <<: *push
    environment:
      URL: ghcr.io
      AUTH: {from_secret: GHCR_IO_AUTH}
