when:
  instance: ci.schnabel.org
  repo: kokuwaio/yamllint
  event: push
  branch: main
  path: [.woodpecker/build.yaml, .woodpecker/push.yaml, .woodpecker/test.yaml, Dockerfile, Dockerfile.dockerignore, entrypoint.sh]

depends_on: [push]
matrix:
  PLATFORM: [amd64, arm64]
labels:
  platform: linux/${PLATFORM}

steps:

  test:
    image: kokuwaio/yamllint
    pull: true
