name: Build

on: push

jobs:

  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - uses: docker/build-push-action@master
        with:
          platforms: linux/amd64,linux/arm64
