name: Lint

on: push

jobs:

  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker://kokuwaio/renovate-config-validator

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker://kokuwaio/markdownlint

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker://kokuwaio/yamllint

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker://kokuwaio/hadolint

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker://kokuwaio/shellcheck
